token: '<INSERT TOKEN HERE>'
chatid: -1
forward: false
messages:
  no_permission: 'NoPermission: permissions.<USERNAME>.<CMD>'
  cmd_success: '<CMD> was executed.'
  cmd_error: '<CMD> was not executed.'
  prefix: '&8[&3TelegramSupport&8] '
  spigot: '&aSpigot libraries loaded'
  bungeecord: '&aBungeecord libraries loaded'
  no_perm: '&cyou do not have permissions to do that!'
  config_loaded: '&aconfig.yml was loaded successfully'
  config_load_error: '&cerror while loading the config.yml'
  spigot_update_available: '&ca newer version is available online'
  spigot_update_api_error: '&cerror while checking for updates'
  telegram_api_error: '&cinvalid botToken and/or chatID'
  telegram_api_error: '&cerror while getting updates from Telegram'
  thread_sleep_error: '&cerror while execution Thread.sleep(8000)'
  metrics_loaded: '&aPlugin-Metrics loaded successfully'
  metrics_error: '&cerror while executing Plugin-Metrics'
  wrong_cmd: '/support <help/join/leave/toggle/reload>'
  help_cmd:
    - '&8------ [&3TelegramSupport&8] -- &6/help&8 ------'
    - '&3/sup join &8- &ajoins the support channel'
    - '&3/sup leave &8- &aleaves the support channel'
    - '&3/sup toggle &8- &aenables/disables this Plugin'
    - '&3/sup info &8- &aprints the plugin description'
    - '&3/sup reload &8- &areloads the config.yml'
    - '&8-------------------------------------'
  reload_cmd: '&aconfig.yml was reloaded successfully'
  toggle_cmd: '&cPlugin disabled. Restart the Server to Enable it again'
  forward_cmd: '&cMessage forwarding toggled.'
  support_join: '&aYou joined the Support-Chatroom'
  support_left: '&cYou left the Support-Chatroom'

permissions-info:
  cmd_join: 'telegramsupport.join'
  cmd_leave: 'telegramsupport.leave'
  cmd_toggle: 'telegramsupport.toggle'
  cmd_forward: 'telegramsupport.forward'
  cmd_reload: 'telegramsupport.reload'
  cmd_help: 'telegramsupport.help'
